import type { Metadata } from "next";

import { SidebarProvider } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"
import { AppNavbar } from "@/components/app-navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarProvider>
      <div className="flex h-screen w-screen overflow-hidden">
        <AppSidebar />
        
        <div className="flex flex-col flex-1 overflow-hidden">
          <AppNavbar />
          <div className="flex-1 overflow-auto p-4">
            {children}
          </div>
        </div>
      </div>
    </SidebarProvider>
  );
}
